# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 937802a4d15edd5d38dd5d72cb0f63937c662883db084e6d7b8da9c53b9c066a3ec26922e68994fb8eb4dc6dd3528223caa0e96d1c77b106c0bf0a9abc55352c

test:
  secret_key_base: 591bded87e7b526b201c0566461066d96668d4f1bccdad481be8d25daad731c67f3e5d5bfb920a021ebdaa9014ac826c323f4c1d8ab0923a83d12d6e867ca2ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
