# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3985bca2116a52667a3e43cd619abd431b3931f59d5cd516548c004bc2bf369d8a7bd1db87d96eb1925acbe19b248f5d961e1f6acdc541be9fe5615884380b4e

test:
  secret_key_base: e36eaade7bd334e46ac5b993db6bf895a1f47ef7dd6f95500514c93b1a22add131171b397a9927d5076020a3504fd5792f080cd6af88787b3d13f93b35e43acd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
